server.port=8080

openweathermap.api.url=https://api.openweathermap.org/data/2.5
# Replace with your actual OpenWeatherMap API key
openweathermap.api.key=YOUR_API_KEY

spring.datasource.url=jdbc:h2:mem:weatherapp;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2c159bf405a415a77038e285d82998782f07293a9c7333d875a6c374eb3dbdd3e51f506eabb717a61d68eb2a2cdbd4bf0
jwt.expiration=86400000
